[tool.poetry]
name = "langroid-examples"
version = "0.1.0"
description = ""
authors = ["Prasad Chalasani <pchalasani@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "examples"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
langroid = "^0.1.18"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
